#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <GL\glew.h>
#include <glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtx/transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <vector>
#include <list>
#include <cassert>
#include <fstream>
#include <iostream>
#include <sstream>
#include <memory>
#include <algorithm>
#include <cctype>
#include <regex>
#include <math.h>
#include <unordered_map>
#include <memory>